config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "lists#index"
  resources :duties

  resources :lists
  get 'calendar' => 'lists#calendar_view', as: :calendar_view

  resources :products

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />  
</head>
<body>
  <div>
    <%= link_to "Home", root_path %>
    <%= link_to "Create new list", new_list_path %>
    <%= link_to "Show all lists", lists_path %>
    <%= link_to "Logout", destroy_user_session_path, :method => :delete%>
    <%= link_to "calendar view", calendar_view_path %>
    <%= link_to "calendar view", calendar_view_path, data: { modal: true } %>

    <%#= link_to 'Create new list', new_list_path, data: { modal: true } %>
    <a href="#" data-reveal-id="myModal">Click Me For A Modal</a>
    <%= link_to "Create new list", new_list_path, data: { :'reveal-id' => 'myModal', :'reveal-ajax' => true } %>
  </div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


  <%= yield %>
  <div id="modal-holder"></div>
  <div id="myModal" class="reveal-modal" data-reveal>
      <%= render :partial => 'lists/form', :locals => { :@list => List.new } %>
      <a class="close-reveal-modal">&#215;</a>
  </div>
</body>
</html>

app/views/layouts/modal.html.erb
<div class='modal' id='mainModal' tabindex='-1' role='dialog' aria-labelledby='mainModalLabel' aria-hidden='true'>
  <div class='modal-dialog'>
    <div class="modal-content">
      <div class="modal-header">
        <button type='button' class='close' data-dismiss='modal'><span aria-hidden='true'>&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="mainModalLabel">
            <%= yield :title if content_for? :title %>&nbsp;
          </h4>
      </div>
      <%= yield %>
    </div>
  </div>
</div>